### ISSUE TITLE
Hyperlinks for rules

### ISSUE THREAD

**Issue by connorjs** [mrcgrtz/stylelint-formatter-pretty#121]
**Is your feature request related to a problem? Please describe.**

I found this formatter when looking for the parallel of `eslint-formatter-pretty` (and I found it!). However, this formatter does not appear to hyperlink to the rules the same way `eslint-formatter-pretty` does.

**Describe the solution you'd like**

This formatter should provide hyperlinks for the rules similar to `eslint-formatter-pretty`.

**Describe alternatives you've considered**

Not use this formatter or build my own.

**Additional context**

This could turn into a "merge from upstream" series of commits, depending on any other parity gaps desired to close.

**Comment by mrcgrtz** [comment]
Thank you, I will take a look at this.

**Comment by mrcgrtz** [comment]
Adding linked rules would require something similar to https://github.com/stefanbuck/eslint-rule-docs for Stylelint which AFAIK does not exist yet.

I might add links to something like `https://stylelint.io/user-guide/rules/<rule-name>` but then it would be limited to Stylelint’s ruleset, but links for custom rules created by plugins would not be possible.

**Comment by connorjs** [comment]
The built-in rules at least have the `url` property. Example: <https://github.com/stylelint/stylelint/blob/main/lib/rules/alpha-value-notation/index.js#L21-L24>
