### ISSUE TITLE
Running 4.0 with pnpm and stylelint cli requires full path

### ISSUE THREAD

**Issue by mscrivo** [mrcgrtz/stylelint-formatter-pretty#160]
**Describe the bug**
We use pnpm and had a package.json script that looks like this:

```
"code-check:stylelint": "stylelint --custom-formatter=node_modules/stylelint-formatter-pretty \"**/*.scss\"",
```

which worked fine, up until 4.0. After upgrading to 4.0 (and stylelint 16), this no longer works. The following error is thrown:

```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/Users/michael/proj/node_modules/stylelint-formatter-pretty' is not supported resolving ES modules imported from /Users/michael/proj/node_modules/.pnpm/stylelint@16.2.1_typescript@5.3.3/node_modules/stylelint/lib/utils/dynamicImport.mjs
Did you mean to import /Users/michael/proj/node_modules/.pnpm/stylelint-formatter-pretty@4.0.0_stylelint@16.2.1/node_modules/stylelint-formatter-pretty/index.js?
    at finalizeResolution (node:internal/modules/esm/resolve:258:11)
    at moduleResolve (node:internal/modules/esm/resolve:917:10)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:328:34)
    at importModuleDynamically (node:internal/modules/esm/translators:158:35)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:207:14)
    at dynamicImport (file:///Users/michael/proj/node_modules/.pnpm/stylelint@16.2.1_typescript@5.3.3/node_modules/stylelint/lib/utils/dynamicImport.mjs:12:68) {
  code: 'ERR_UNSUPPORTED_DIR_IMPORT',
  url: 'file:///Users/michael/proj/node_modules/stylelint-formatter-pretty'
}

Node.js v20.11.0
```

It does work, if I provide the full path:

```
pnpm stylelint --custom-formatter=node_modules/.pnpm/stylelint-formatter-pretty@4.0.0_stylelint@16.2.1/node_modules/stylelint-formatter-pretty/index.js
```

but that is unsightly and will need to be updated every time versions change. Is this expected? Is there another way to get this working?

**To Reproduce**

Add stylelint, stylelint-formatter-pretty to your package.json. Run pnpm install and then try:
```
pnpm stylelint --custom-formatter=node_modules/stylelint-formatter-pretty
```

**Expected behavior**
It should work without specifying the full path to index.js

**Versions:**
 - OS: macOS 14.3.1
 - Node: 20.11
 - Package: v4 & stylelint v16.2

**Additional context**

**Comment by mrcgrtz** [comment]
Thanks for reporting this, I will take a look at it.

Maybe the exports are not working for `pnpm`. Have you tried other 3rd party Stylelint formatters, are they working as expected?

**Comment by mscrivo** [comment]
> Thanks for reporting this, I will take a look at it.
> 
> Maybe the exports are not working for `pnpm`. Have you tried other 3rd party Stylelint formatters, are they working as expected?

I have not yet, will let you know any findings there if I can find some time to find and try one.

**Comment by mrcgrtz** [comment]
This is actually working for me:

```shell
pnpm stylelint --custom-formatter stylelint-formatter-pretty *.css
```

Note the missing `node_modules/`.

I also tested this with `npx` and `yarn`, works like a charm.

Apparently the documentation for using the formatter [with Stylelint’s CLI](https://github.com/mrcgrtz/stylelint-formatter-pretty?tab=readme-ov-file#stylelint-cli) isn’t up-to-date (but the screenshot is).

Can you check if it works for you that way? Then I would update the documentation.

**Comment by mscrivo** [comment]
That does indeed work! Thank you
